services:
    innovare.admin.afferenza:
        class: Application\Innovare\CoreBundle\Admin\AfferenzaAdmin
        arguments: [~, Application\Innovare\ModelBundle\Entity\Afferenza, ApplicationInnovareCoreBundle:AfferenzaAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Afferenza}

    innovare.admin.macroarea:
        class: Application\Innovare\CoreBundle\Admin\MacroareaAdmin
        arguments: [~, Application\Innovare\ModelBundle\Entity\Macroarea, ApplicationInnovareCoreBundle:MacroareaAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Macroarea}

    innovare.admin.strumenti:
        class: Application\Innovare\CoreBundle\Admin\StrumentiAdmin
        arguments: [~, Application\Innovare\ModelBundle\Entity\Strumenti, ApplicationInnovareCoreBundle:StrumentiAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Strumenti}

    innovare.admin.laboratorio:
        class: Application\Innovare\CoreBundle\Admin\LaboratorioAdmin
        arguments: [~, Application\Innovare\ModelBundle\Entity\Laboratorio, ApplicationInnovareCoreBundle:LaboratorioAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Laboratorio}

    innovare.admin.anagrafica_rilevatori:
        class: Application\Innovare\CoreBundle\Admin\AnagraficaRilevatoriAdmin
        arguments: [~, Application\Innovare\ModelBundle\Entity\AnagraficaRilevatori, ApplicationInnovareCoreBundle:AnagraficaRilevatoriAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: AnagraficaRilevatori}

    innovare.admin.ambito_intervento:
        class: Application\Innovare\CoreBundle\Admin\AmbitoInterventoAdmin
        arguments: [~, Application\Innovare\ModelBundle\Entity\AmbitoIntervento, ApplicationInnovareCoreBundle:AmbitoInterventoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: AmbitoIntervento}

    innovare.admin.area:
        class: Application\Innovare\CoreBundle\Admin\AreaAdmin
        arguments: [~, Application\Innovare\ModelBundle\Entity\Area, ApplicationInnovareCoreBundle:AreaAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Area}
