services:
    innovare.admin.afferenza:
        class: Application\Innovare\CoreBundle\Admin\AfferenzaAdmin
        arguments: [~, Application\Innovare\ModelBundle\Entity\Afferenza, ApplicationInnovareCoreBundle:AfferenzaAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Afferenza}

    innovare.admin.macroarea:
        class: Application\Innovare\CoreBundle\Admin\MacroareaAdmin
        arguments: [~, Application\Innovare\ModelBundle\Entity\Macroarea, ApplicationInnovareCoreBundle:MacroareaAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Macroarea}

    innovare.admin.strumenti:
        class: Application\Innovare\CoreBundle\Admin\StrumentiAdmin
        arguments: [~, Application\Innovare\ModelBundle\Entity\Strumenti, ApplicationInnovareCoreBundle:StrumentiAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Strumenti}
