services:
    innovare.admin.afferenza:
        class: Application\Innovare\CoreBundle\Admin\AfferenzaAdmin
        arguments: [~, Application\Innovare\ModelBundle\Entity\Afferenza, ApplicationInnovareCoreBundle:AfferenzaAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Afferenza}

    innovare.admin.macroarea:
        class: Application\Innovare\CoreBundle\Admin\MacroareaAdmin
        arguments: [~, Application\Innovare\ModelBundle\Entity\Macroarea, ApplicationInnovareCoreBundle:MacroareaAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Macroarea}

    innovare.admin.strumenti:
        class: Application\Innovare\CoreBundle\Admin\StrumentiAdmin
        arguments: [~, Application\Innovare\ModelBundle\Entity\Strumenti, ApplicationInnovareCoreBundle:StrumentiAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Strumenti}

    innovare.admin.laboratorio:
        class: Application\Innovare\CoreBundle\Admin\LaboratorioAdmin
        arguments: [~, Application\Innovare\ModelBundle\Entity\Laboratorio, ApplicationInnovareCoreBundle:LaboratorioAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Laboratorio}

    innovare.admin.anagrafica_rilevatori:
        class: Application\Innovare\CoreBundle\Admin\AnagraficaRilevatoriAdmin
        arguments: [~, Application\Innovare\ModelBundle\Entity\AnagraficaRilevatori, ApplicationInnovareCoreBundle:AnagraficaRilevatoriAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Anagrafica Rilevatori}

    innovare.admin.ambito_intervento:
        class: Application\Innovare\CoreBundle\Admin\AmbitoInterventoAdmin
        arguments: [~, Application\Innovare\ModelBundle\Entity\AmbitoIntervento, ApplicationInnovareCoreBundle:AmbitoInterventoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Ambito di Intervento}

    innovare.admin.area:
        class: Application\Innovare\CoreBundle\Admin\AreaAdmin
        arguments: [~, Application\Innovare\ModelBundle\Entity\Area, ApplicationInnovareCoreBundle:AreaAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Area}

    innovare.admin.attivita_didattica:
        class: Application\Innovare\CoreBundle\Admin\AttivitaDidatticaAdmin
        arguments: [~, Application\Innovare\ModelBundle\Entity\AttivitaDidattica, ApplicationInnovareCoreBundle:AttivitaDidatticaAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Attività Didattica}

    innovare.admin.attivita_ricerca:
        class: Application\Innovare\CoreBundle\Admin\AttivitaRicercaAdmin
        arguments: [~, Application\Innovare\ModelBundle\Entity\AttivitaRicerca, ApplicationInnovareCoreBundle:AttivitaRicercaAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Attività di Ricerca}

    innovare.admin.laboratorio_tecnici:
        class: Application\Innovare\CoreBundle\Admin\LaboratorioTecniciAdmin
        arguments: [~, Application\Innovare\ModelBundle\Entity\LaboratorioTecnici, ApplicationInnovareCoreBundle:LaboratorioTecniciAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Tecnici Laboratorio}

    innovare.admin.ente:
        class: Application\Innovare\CoreBundle\Admin\EnteAdmin
        arguments: [~, Application\Innovare\ModelBundle\Entity\Ente, ApplicationInnovareCoreBundle:EnteAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Ente}

